//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Legal_Buyers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Legal_Buyers()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public string Firm { get; set; }
        public string FIODir { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        public string Indexx { get; set; }
        public string Republic { get; set; }
        public string City { get; set; }
        public string MKR { get; set; }
        public string Street { get; set; }
        public string Dormitory { get; set; }
        public string House { get; set; }
        public string Flat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
