//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public string DateOfOrder { get; set; }
        public string DateSend { get; set; }
        public string ManagerId { get; set; }
        public string BuyerId { get; set; }
        public string StoreKeeperId { get; set; }
    
        public virtual Legal_Buyers Legal_Buyers { get; set; }
        public virtual Managers Managers { get; set; }
        public virtual Physical_Buyers Physical_Buyers { get; set; }
        public virtual Storekeepers Storekeepers { get; set; }
    }
}
